adf

diff --git a/.github/workflows/create-pr.yml b/.github/workflows/create-pr.yml
--- a/.github/workflows/create-pr.yml
+++ b/.github/workflows/create-pr.yml
@@ -109,24 +109,20 @@ jobs:
       - name: Enable automerge
         shell: bash
         run: |
-          # gh pr merge -R "${{ github.repository }}" --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
-          # auto_merge_status=$(curl -X PATCH \
-          # -H "Accept: application/vnd.github.v3+json" \
-          # -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          # https://api.github.com/repos/ajinkyak423/actions-poc/pulls/${{ steps.cpr.outputs.pull-request-number }} \
-          # -d '{"auto_merge": true}' \
-          # | jq '.auto_merge' \
-          # | tr -d '"')
-          # echo "auto_merge_status=$auto_merge_status"
-
-          # Enable auto-merge with squash merging
-          curl -X PATCH \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          response=$(curl -X PATCH \
+            -H "Authorization: token ${{ secrets.MY_GITHUB_ACTION_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
-            -d '{"auto_merge": "true", "merge_method": "squash"}' \
-            "https://api.github.com/repos/ajinkyak423/actions-poc/pulls/${{ steps.cpr.outputs.pull-request-number }}"
+            -d '{"auto_merge": true, "merge_method": "squash"}' \
+            "https://api.github.com/repos/ajinkyak423/actions-poc/pulls/${{ steps.cpr.outputs.pull-request-number }}")
+          
+          echo "Response: $response"
 
-          # echo "Auto-merge with squash merge enabled for PR $pull_number."
+          if [[ "$response" == *"\"message\": \"Validation Failed\""* ]]; then
+            echo "Validation Failed: Auto-merge with squash merge could not be enabled."
+            exit 1
+          fi
+
+          echo "Auto-merge with squash merge enabled successfully."
 
 
 
